spring.application.name=aggregation-cbs

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.hibernate.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
#spring.datasource.url=jdbc:oracle:thin:@41.86.8.78:19093/ALTBANK
spring.datasource.url=jdbc:oracle:thin:@172.19.49.214:1521/ALTBANK
spring.datasource.username=ALTBANK
spring.datasource.password=BANKLB30012011
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

#logging.level.root=info
#logging.level.org.hibernate.SQL=trace
#logging.level.org.hibernate.type.descriptor.sql=trace

server.servlet.context-path=/account-mapper-cbs
server.port=9227
springdoc.swagger-ui.path=/api-doc.html
springdoc.swagger-ui.operationsSorter=method

fixedDelay.in.milliseconds.forInsertElementIntoOperation=5000

security.listOfAcceptedAddress=127.0.0.1,0:0:0:0:0:0:0:1